CREATE UNLOGGED TABLE "staging_parcels" (
	"row_num" serial PRIMARY KEY NOT NULL,
	"address" varchar NOT NULL,
	"city" varchar,
	"zip_code" varchar(10),
	"county" varchar,
	"owner_name_1" varchar,
	"owner_name_2" varchar,
	"property_type" varchar,
	"year_built" integer,
	"square_footage" integer,
	"land_area" numeric(14, 4),
	"land_unit" varchar(2),
	"bldg_story" numeric(5, 1),
	"desc_style" varchar,
	"ooi" varchar(2),
	"legal1" varchar,
	"legal2" varchar,
	"legal3" varchar,
	"zoning" varchar,
	"assessor_id" varchar,
	"latitude" numeric(10, 7),
	"longitude" numeric(10, 7),
	"sale_date" varchar(10),
	"sale_price" integer,
	"seller" varchar,
	"document_type" varchar,
	"nfm_land_value" numeric(12, 2),
	"nfm_improvement_value" numeric(12, 2),
	"nfm_total_value" numeric(12, 2),
	"subdivision" varchar,
	"raw_data" jsonb
);
