packages:
  - "apps/*"
onlyBuiltDependencies:
  - "@datadog/native-appsec"
  - "@datadog/native-iast-taint-tracking"
  - "@datadog/native-metrics"
  - "@datadog/pprof"
  - "@nestjs/core"
  - bufferutil
  - dd-trace
  - playwright
  - sharp
  - unrs-resolver
